.pragma library
/*
    MusicDatabase75.js - contains song data to build music db with ~75 albums
*/

var musicRawData=[

["","Planet Telex ","04:18",1,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","The Bends ","04:06",2,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","High And Dry ","04:18",3,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","Fake Plastic Trees ","04:50",4,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","Bones ","03:09",5,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","Nice Dream","03:53",6,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","Just ","03:55",7,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","My Iron Lung ","04:36",8,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","Bullet Proof... I Wish I Was ","03:29",9,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","Black Star ","04:07",10,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","Sulk ","03:43",11,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","Street Spirit (Fade Out) ","04:12",12,"The Bends","Radiohead","Alternative Rock",1995,"pics/album_radiohead_thebends.png"],
["","15 Step ","03:57",1,"In Rainbows","Radiohead","Alternative Rock",2007,"pics/album_radiohead_inrainbows.png"],
["","Bodysnatchers ","04:02",2,"In Rainbows","Radiohead","Alternative Rock",2007,"pics/album_radiohead_inrainbows.png"],
["","Nude ","04:15",3,"In Rainbows","Radiohead","Alternative Rock",2007,"pics/album_radiohead_inrainbows.png"],
["","Weird Fishes/Arpeggi ","05:18",4,"In Rainbows","Radiohead","Alternative Rock",2007,"pics/album_radiohead_inrainbows.png"],
["","All I Need ","03:49",5,"In Rainbows","Radiohead","Alternative Rock",2007,"pics/album_radiohead_inrainbows.png"],
["","Faust Arp ","02:10",6,"In Rainbows","Radiohead","Alternative Rock",2007,"pics/album_radiohead_inrainbows.png"],
["","Reckoner ","04:50",7,"In Rainbows","Radiohead","Alternative Rock",2007,"pics/album_radiohead_inrainbows.png"],
["","House Of Cards ","05:28",8,"In Rainbows","Radiohead","Alternative Rock",2007,"pics/album_radiohead_inrainbows.png"],
["","Jigsaw Falling Into Place ","04:09",9,"In Rainbows","Radiohead","Alternative Rock",2007,"pics/album_radiohead_inrainbows.png"],
["","Videotape ","04:40",10,"In Rainbows","Radiohead","Alternative Rock",2007,"pics/album_radiohead_inrainbows.png"],
["","2 + 2 = 5 ","03:24",1,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","Sit Down. Stand Up. ","04:15",2,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","Sail To The Moon. ","04:28",3,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","Backdrifts. ","05:32",4,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","Go To Sleep. ","03:31",5,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","Where I End And You Begin. ","04:34",6,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","We Suck Young Blood. ","04:59",7,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","The Gloaming. ","04:23",8,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","There There. ","05:25",9,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","I Will. ","02:25",10,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","A Punchup At A Wedding. ","04:54",11,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","Myxomatosis. ","03:58",12,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","Scatterbrain. ","03:24",13,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","A Wolf At The Door. ","03:25",14,"Hail To The Thief","Radiohead","Alternative Rock",2003,"pics/album_radiohead_hailtothethief.png"],
["","Sunburn ","03:54",1,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Muscle Museum ","04:23",2,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Fillip ","04:01",3,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Falling Down ","04:34",4,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Cave ","04:46",5,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Showbiz ","05:16",6,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Unintended ","03:57",7,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Uno ","03:38",8,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Sober ","04:04",9,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Escape ","03:31",10,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Overdue ","02:26",11,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","Hate This & I'll Love You ","05:09",12,"Showbiz","Muse","Rock",1999,"pics/album_muse_showbiz.png"],
["","New Born ","06:02",1,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Bliss ","04:12",2,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Space Dementia ","06:21",3,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Hyper Music ","03:21",4,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Plug In Baby ","03:40",5,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Citizen Erased ","07:19",6,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Micro Cuts ","03:38",7,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Screenager ","04:20",8,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Darkshines ","04:47",9,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Feeling Good ","03:19",10,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Megalomania ","04:37",11,"Origin Of Symmetry","Muse","Rock",2001,"pics/album_muse_originofsymmetry.png"],
["","Uprising ","05:03",1,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","Resistance ","05:47",2,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","Undisclosed Desires ","03:56",3,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","United States Of Eurasia (+Collateral Damage) ","05:48",4,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","Guiding Light ","04:13",5,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","Unnatural Selection ","06:55",6,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","Mk Ultra ","04:06",7,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","I Belong To You (+Mon Cœur S'Ouvre A Ta Voix) ","05:39",8,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","Exogenesis: Symphony Part I (Overture) ","04:18",9,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","Exogenesis: Symphony Part II (Cross-Pollination) ","03:56",10,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","Exogenesis: Symphony Part III (Redemption) ","04:37",11,"The Resistance","Muse","Rock",2009,"pics/album_muse_theresistance.png"],
["","All The Lovers ","03:20",1,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Get Outta My Way ","03:39",2,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Put Your Hands Up (If You Feel Love) ","03:38",3,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Closer ","03:09",4,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Everything Is Beautiful ","03:26",5,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Aphrodite ","03:46",6,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Illusion ","03:22",7,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Better Than Today ","03:25",8,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Too Much ","03:16",9,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Cupid Boy ","04:27",10,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Looking For An Angel ","03:50",11,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Can't Beat The Feeling ","04:11",12,"Aphrodite","Kylie","Pop",2010,"pics/album_kylie_aphrodite.png"],
["","Slow ","03:15",1,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","Still Standing ","03:40",2,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","Secret (Take You Home) ","03:16",3,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","Promises ","03:17",4,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","Sweet Music ","04:11",5,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","Red Blooded Woman ","04:21",6,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","Chocolate ","05:00",7,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","Obsession ","03:31",8,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","I Feel For You ","04:19",9,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","Someday ","04:18",10,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","Loving Days ","04:26",11,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","After Dark ","04:10",12,"Body Language","Kylie","Pop",2003,"pics/album_kylie_bodylanguage.png"],
["","Dog Days Are Over ","04:00",1,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","Rabbit Heart (Raise It Up) ","04:00",2,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","I'm Not Calling You A Liar ","04:00",3,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","Howl ","04:00",4,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","Kiss With A Fist ","04:00",5,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","Girl With One Eye ","04:00",6,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","Drumming Song ","04:00",7,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","Between Two Lungs ","04:00",8,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","Cosmic Love ","04:00",9,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","My Boy Builds Coffins ","04:00",10,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","Hurricane Drunk ","04:00",11,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","Blinding ","04:00",12,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","Bonus Track ","04:00",13,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
["","You've Got The Love","04:00",14,"Lungs","Florence + The Machine","Pop",2009,"pics/album_florenceandthemachine_lungs.png"],
[""," Wake  ","01:40",1,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","Given Up ","03:09",2,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","Leave Out All The Rest ","03:29",3,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","Bleed It Out ","02:44",4,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","Shadow Of The Day ","04:49",5,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","What I've Done ","03:25",6,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","Hands Held High ","03:53",7,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","No More Sorrow ","03:41",8,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","Valentine's Day ","03:16",9,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","In Between ","03:16",10,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","In Pieces ","03:38",11,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","The Little Things Give You Away ","06:23",12,"Minutes To Midnight","Linkin Park","Rock",2007,"pics/album_linkinpark_minutestomidnight.png"],
["","Here Comes Santa Claus (Right Down Santa Claus Lane)  ","01:44",1,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","Up On The House-Top ","01:32",2,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","Silver Bells ","01:32",3,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","Rudolph The Red-Nosed Reindeer ","02:32",4,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","Jingle Bells ","02:36",5,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","Over The River And Through The Woods ","01:56",6,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","Santa Claus Is Comin' To Town ","01:44",7,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","It's Beginning To Look Like Christmas ","01:45",8,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","Frosty The Snow Man ","01:59",9,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","White Christmas ","02:33",10,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","The Chipmunk Song ","02:19",11,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","We Wish You A Merry Christmas ","01:53",12,"Christmas With The Chipmunks","The Chipmunks","Pop",1962,"pics/album_chipmunks_xmas.png"],
["","Just Dance (Space Cowboy Remix) ","05:02",1,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Just Dance (RedOne Remix) ","04:20",2,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Poker Face (Space Cowboy Remix) ","04:55",3,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Poker Face (LGG Vs GLG Radio Mix) ","04:03",4,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Eh, Eh (Nothing Else I Can Say) (Electric Piano And Human Beat Box Version - The Cherrytree Sessions Version) ","03:04",5,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Eh, Eh (Nothing Else I Can Say) (Pet Shop Boys Radio Remix) ","02:50",6,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","LoveGame (Space Cowboy Remix) ","03:21",7,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","LoveGame (Chew Fu Ghettohouse Fix Feat. Marilyn Manson) ","05:21",8,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Paparazzi (Yuksek Remix) ","04:48",9,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Paparazzi (Stuart Price Remix) ","03:20",10,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Bad Romance (Skrillex Radio Remix) ","04:24",11,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Bad Romance (Starsmith Remix) ","04:57",12,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Bad Romance (Kaskade Main Remix) ","04:22",13,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Telephone Feat. Beyoncé (Alphabeat Remix) ","04:50",14,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Telephone Feat. Beyoncé (Passion Pit Remix) ","05:14",15,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Telephone Feat. Beyoncé (Crookers Vocal Remix) ","04:50",16,"The Remix","Lady Gaga","Electronic",2010,"pics/album_ladygaga_remix.png"],
["","Harder To Breathe  ","02:53",1,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","This Love ","03:26",2,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","Shiver ","02:59",3,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","She Will Be Loved ","04:17",4,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","Tangled ","03:18",5,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","The Sun ","04:11",6,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","Must Get Out ","03:59",7,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","Sunday Morning ","04:06",8,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","Secret ","04:55",9,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","Through With You ","03:01",10,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","Not Coming Home ","04:21",11,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","Sweetest Goodbye ","04:32",12,"Songs About Jane","Maroon 5","Rock",2003,"pics/album_maroon5_songsaboutjane.png"],
["","Smells Like Teen Spirit  ","05:02",1,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","In Bloom ","04:15",2,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Come As You Are ","03:39",3,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Breed ","03:04",4,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Lithium ","04:17",5,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Polly ","02:56",6,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Territorial Pissings ","02:23",7,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Drain You ","03:44",8,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Lounge Act ","02:37",9,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Stay Away ","03:33",10,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","On A Plain ","03:17",11,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Something In The Way ","03:51",12,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Endless, Nameless ","06:44",13,"Nevermind","Nirvana","Rock",1991,"pics/album_nirvana_nevermind.png"],
["","Love Goes Down  ","04:00",1,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","Writing's On The Wall ","04:00",2,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","Stay Too Long ","04:00",3,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","She Said ","04:00",4,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","Welcome To Hell ","04:00",5,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","Hard Times ","04:00",6,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","The Recluse ","04:00",7,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","Traded In My Cigarettes ","04:00",8,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","Prayin' ","04:00",9,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","Darkest Place ","04:00",10,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","Free ","04:00",11,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","I Know A Song ","04:00",12,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","What You Gonna Do ","04:00",13,"The Defamation Of Strickland Banks","Plan B","Rock",2010,"pics/album_planb_defamationofstricklandbanks.png"],
["","Airbag  ","04:44",1,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","Paranoid Android ","06:23",2,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","Subterranean Homesick Film ","04:28",3,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","Exit Music (For A Film) ","04:25",4,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","Let Down ","04:59",5,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","Karma Police ","04:22",6,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","Fitter Happier ","01:57",7,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","Electioneering ","03:51",8,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","Climbing Up The Walls ","04:45",9,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","No Surprises ","03:49",10,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","No Lucky ","04:20",11,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","The Tourist ","05:25",12,"OK Computer","Radiohead","Alternative Rock",1997,"pics/album_radiohead_okcomputer.png"],
["","You ","03:28",1,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","Creep ","03:55",2,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","How Do You? ","02:12",3,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","Stop Whispering ","05:25",4,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","Thinking About You ","02:41",5,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","Anyone Can Play Guitar ","03:37",6,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","Ripcord ","03:09",7,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","Vegetable ","03:12",8,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","Prove Yourself ","02:25",9,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","I Can't ","04:13",10,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","Lurgee ","03:07",11,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","Blow Out ","04:40",12,"Pablo Honey","Radiohead","Alternative Rock",1993,"pics/album_radiohead_pablohoney.png"],
["","Night Work  ","03:08",1,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Whole New Way ","02:54",2,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Fire With Fire ","04:13",3,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Any Which Way ","04:41",4,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Harder You Get ","03:06",5,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Running Out ","03:09",6,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Something Like This ","03:02",7,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Skin This Cat ","02:41",8,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Skin Tight ","03:26",9,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Sex And Violence ","04:10",10,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Night Life ","03:37",11,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Invisible Light ","06:15",12,"Night Work","Scissor Sisters","Electronic",2010,"pics/album_scissorsisters_nightwork.png"],
["","Wannabe ","02:54",1,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Say You'll Be There ","03:57",2,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","2 Become 1 ","04:04",3,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Mama ","03:41",4,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Who Do You Think You Are ","03:45",5,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Move Over ","02:43",6,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Spice Up Your Life ","02:55",7,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Too Much ","02:53",8,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Stop ","03:25",9,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Viva Forever ","04:13",10,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Let Love Lead The Way ","04:16",11,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Holler ","03:56",12,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Headlines (Friendship Never Ends) ","03:30",13,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Voodoo ","03:11",14,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Goodbye ","04:21",15,"Greatest Hits","Spice Girls","Pop",2007,"pics/album_spicegirls_greatesthits.png"],
["","Love Me Do ","02:23",1,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","From Me To You ","01:57",2,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Thank You Girl ","02:04",3,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","She Loves You ","02:21",4,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","I'll Get You ","02:05",5,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","I Want To Hold Your Hand ","02:26",6,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","This Boy ","02:16",7,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Komm, Gib Mir Deine Hand ","02:26",8,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Sie Liebt Dich ","02:19",9,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Long Tall Sally ","02:03",10,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","I Call Your Name ","02:09",11,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Slow Down ","02:56",12,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Matchbox ","01:58",13,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","I Feel Fine ","02:19",14,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","She's A Woman ","03:03",15,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Bad Boy ","02:02",16,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Yes It Is ","02:42",17,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","I'm Down ","02:31",18,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Day Tripper ","02:00",19,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","We Can Work It Out ","02:00",20,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Paperback Writer ","02:00",21,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Rain ","02:00",22,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Lady Madonna ","02:00",23,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","The Inner Light ","02:00",24,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Hey Jude ","02:00",25,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Revolution ","02:00",26,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Get Back ","02:00",27,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Don't Let Me Down ","02:00",28,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","The Ballad Of John And Yoko ","02:00",29,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Old Brown Shoe ","02:00",30,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Across The Universe ","02:00",31,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Let It Be ","02:00",32,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","You Know My Name (Look Up The Number) ","02:00",33,"Past Masters","The Beatles","Rock",1988,"pics/album_thebeatles_pastmasters.png"],
["","Spitfire","05:08",1,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","Girls","04:07",2,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","Memphis Bells","04:29",3,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","Get Up Get Off","04:20",4,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","Hot Ride","04:36",5,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","Wake Up Call","04:56",6,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","Action Radar","05:33",7,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","Medusa's Path","06:09",8,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","Phoenix","04:39",9,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","You'll Be Under My Wheels","03:57",10,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","The Way It Is","05:46",11,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","Shoot Down","04:32",12,"Always Outnumbered Never Outgunned","The Prodigy","Breakbeat",2004,"pics/album_prodigy_alwaysoutnumbered.png"],
["","soldier of fortune","05:08",1,"Bad Reputation","Thin Lizzy","Rock",,"pics/album_thinlizzy_badreputation.png"],
["","bad reputation","03:03",2,"Bad Reputation","Thin Lizzy","Rock",,"pics/album_thinlizzy_badreputation.png"],
["","opium trail","03:50",3,"Bad Reputation","Thin Lizzy","Rock",,"pics/album_thinlizzy_badreputation.png"],
["","southbound","04:16",4,"Bad Reputation","Thin Lizzy","Rock",,"pics/album_thinlizzy_badreputation.png"],
["","dancing in the moonlight","03:18",5,"Bad Reputation","Thin Lizzy","Rock",,"pics/album_thinlizzy_badreputation.png"],
["","killer without a cause","03:27",6,"Bad Reputation","Thin Lizzy","Rock",,"pics/album_thinlizzy_badreputation.png"],
["","downtown sundown","03:59",7,"Bad Reputation","Thin Lizzy","Rock",,"pics/album_thinlizzy_badreputation.png"],
["","that womans gonna break your h","03:20",8,"Bad Reputation","Thin Lizzy","Rock",,"pics/album_thinlizzy_badreputation.png"],
["","dear lord","04:16",9,"Bad Reputation","Thin Lizzy","Rock",,"pics/album_thinlizzy_badreputation.png"],
["","do anything you want to","03:44",1,"Black Rose","Thin Lizzy","Rock",,"pics/album_thinlizzy_blackrose.png"],
["","toughest street in town","03:51",2,"Black Rose","Thin Lizzy","Rock",,"pics/album_thinlizzy_blackrose.png"],
["","s and m","03:58",3,"Black Rose","Thin Lizzy","Rock",,"pics/album_thinlizzy_blackrose.png"],
["","waiting for an alibi","03:23",4,"Black Rose","Thin Lizzy","Rock",,"pics/album_thinlizzy_blackrose.png"],
["","sarah","03:20",5,"Black Rose","Thin Lizzy","Rock",,"pics/album_thinlizzy_blackrose.png"],
["","got to give it up","04:14",6,"Black Rose","Thin Lizzy","Rock",,"pics/album_thinlizzy_blackrose.png"],
["","get out of here","03:27",7,"Black Rose","Thin Lizzy","Rock",,"pics/album_thinlizzy_blackrose.png"],
["","with love","04:28",8,"Black Rose","Thin Lizzy","Rock",,"pics/album_thinlizzy_blackrose.png"],
["","black rose a rock legend","06:51",9,"Black Rose","Thin Lizzy","Rock",,"pics/album_thinlizzy_blackrose.png"],
["","typical male","04:18",1,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","what you see is what you get","04:32",2,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","two people","04:12",3,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","till the right man comes along","04:11",4,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","afterglow","04:31",5,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","girls","04:56",6,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","back to where you started","04:28",7,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","break every rule","04:02",8,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","overnoght sensation","04:40",9,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","paradise is here","05:36",10,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","ill be there","05:21",11,"Break Every Rule","Tina Turner","Pop",,"pics/album_tinaturner_breakeveryrule.png"],
["","we will be strong","05:03",1,"Chinatown","Thin Lizzy","Rock",,"pics/album_thinlizzy_chinatown.png"],
["","chinatown","04:36",2,"Chinatown","Thin Lizzy","Rock",,"pics/album_thinlizzy_chinatown.png"],
["","sweetheart","03:20",3,"Chinatown","Thin Lizzy","Rock",,"pics/album_thinlizzy_chinatown.png"],
["","sugar blues","04:14",4,"Chinatown","Thin Lizzy","Rock",,"pics/album_thinlizzy_chinatown.png"],
["","killer on the loose","03:47",5,"Chinatown","Thin Lizzy","Rock",,"pics/album_thinlizzy_chinatown.png"],
["","having a good time","04:29",6,"Chinatown","Thin Lizzy","Rock",,"pics/album_thinlizzy_chinatown.png"],
["","genocide","04:59",7,"Chinatown","Thin Lizzy","Rock",,"pics/album_thinlizzy_chinatown.png"],
["","didnt i","04:17",8,"Chinatown","Thin Lizzy","Rock",,"pics/album_thinlizzy_chinatown.png"],
["","hey you","04:59",9,"Chinatown","Thin Lizzy","Rock",,"pics/album_thinlizzy_chinatown.png"],
["","Coles Corner","04:49",1,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","Just Like The Rain","03:18",2,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","Hotel Room","03:43",3,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","Darlin Wait For Me","03:54",4,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","The Ocean","05:37",5,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","Born Under A Bad Sign","03:41",6,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","I Sleep Alone","03:45",7,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","Tonight","04:32",8,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","Wading Through The Waters Of M","03:49",9,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","Whos Gonna Shoe Your Pretty Li","04:08",10,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","Last Orders","04:59",11,"Coles Corner","Richard Hawley","Rock",,"pics/album_richardhawley_colescorner.png"],
["","Horchata","03:27",1,"Contra","Vampire Weekend","Alternative",2010,"pics/album_vampireweekend_contra.png"],
["","White Sky","02:59",2,"Contra","Vampire Weekend","Alternative",2010,"pics/album_vampireweekend_contra.png"],
["","Holiday","02:18",3,"Contra","Vampire Weekend","Alternative",2010,"pics/album_vampireweekend_contra.png"],
["","California English","02:30",4,"Contra","Vampire Weekend","Alternative",2010,"pics/album_vampireweekend_contra.png"],
["","Taxi Cab","03:56",5,"Contra","Vampire Weekend","Alternative",2010,"pics/album_vampireweekend_contra.png"],
["","Run","03:53",6,"Contra","Vampire Weekend","Alternative",2010,"pics/album_vampireweekend_contra.png"],
["","Cousins","02:25",7,"Contra","Vampire Weekend","Alternative",2010,"pics/album_vampireweekend_contra.png"],
["","Giving Up The Gun","04:46",8,"Contra","Vampire Weekend","Alternative",2010,"pics/album_vampireweekend_contra.png"],
["","Diplomat's Son","06:01",9,"Contra","Vampire Weekend","Alternative",2010,"pics/album_vampireweekend_contra.png"],
["","I Think Ur A Contra","04:26",10,"Contra","Vampire Weekend","Alternative",2010,"pics/album_vampireweekend_contra.png"],
["","rosalie","02:52",1,"Fighting","Thin Lizzy","Rock",1975,"pics/album_thinlizzy_fighting.png"],
["","for those who love to live","03:07",2,"Fighting","Thin Lizzy","Rock",1975,"pics/album_thinlizzy_fighting.png"],
["","suicide","05:08",3,"Fighting","Thin Lizzy","Rock",1975,"pics/album_thinlizzy_fighting.png"],
["","wild one","04:14",4,"Fighting","Thin Lizzy","Rock",1975,"pics/album_thinlizzy_fighting.png"],
["","fighting my way back","03:11",5,"Fighting","Thin Lizzy","Rock",1975,"pics/album_thinlizzy_fighting.png"],
["","kings vengeance","04:04",6,"Fighting","Thin Lizzy","Rock",1975,"pics/album_thinlizzy_fighting.png"],
["","spirit slips away","04:30",7,"Fighting","Thin Lizzy","Rock",1975,"pics/album_thinlizzy_fighting.png"],
["","silver dollar","03:23",8,"Fighting","Thin Lizzy","Rock",1975,"pics/album_thinlizzy_fighting.png"],
["","freedom song","03:26",9,"Fighting","Thin Lizzy","Rock",1975,"pics/album_thinlizzy_fighting.png"],
["","ballad of the hard man","03:10",10,"Fighting","Thin Lizzy","Rock",1975,"pics/album_thinlizzy_fighting.png"],
["","Show Down","05:28",1,"In Silico","Pendulum","Electronica",2008,"pics/album_pendulum_insilico.png"],
["","Different","05:52",2,"In Silico","Pendulum","Electronica",2008,"pics/album_pendulum_insilico.png"],
["","Propane Nightmares","05:13",3,"In Silico","Pendulum","Electronica",2008,"pics/album_pendulum_insilico.png"],
["","Visions","05:36",4,"In Silico","Pendulum","Electronica",2008,"pics/album_pendulum_insilico.png"],
["","Midnight Runner","06:55",5,"In Silico","Pendulum","Electronica",2008,"pics/album_pendulum_insilico.png"],
["","The Other Side","05:16",6,"In Silico","Pendulum","Electronica",2008,"pics/album_pendulum_insilico.png"],
["","Mutiny","05:10",7,"In Silico","Pendulum","Electronica",2008,"pics/album_pendulum_insilico.png"],
["","9,000 Miles","06:26",8,"In Silico","Pendulum","Electronica",2008,"pics/album_pendulum_insilico.png"],
["","Granite","04:42",9,"In Silico","Pendulum","Electronica",2008,"pics/album_pendulum_insilico.png"],
["","The Tempest","07:27",10,"In Silico","Pendulum","Electronica",2008,"pics/album_pendulum_insilico.png"],
["","Invaders Must Die","04:55",1,"Invaders Must Die","The Prodigy","Breakbeat",2009,"pics/album_prodigy_invadersmustdie.png"],
["","Omen","03:36",2,"Invaders Must Die","The Prodigy","Breakbeat",2009,"pics/album_prodigy_invadersmustdie.png"],
["","Colours","03:28",4,"Invaders Must Die","The Prodigy","Breakbeat",2009,"pics/album_prodigy_invadersmustdie.png"],
["","Omen Reprise","02:14",8,"Invaders Must Die","The Prodigy","Breakbeat",2009,"pics/album_prodigy_invadersmustdie.png"],
["","Piranha","04:05",10,"Invaders Must Die","The Prodigy","Breakbeat",2009,"pics/album_prodigy_invadersmustdie.png"],
["","Zero [Instrumental]","04:26",1,"It's Blitz [Instrumental Versions]","Yeah Yeah Yeahs","Post-Punk Revival",2009,"pics/album_yeahyeahyeahs_itsblitz.png"],
["","Heads Will Roll [Instrumental]","03:42",2,"It's Blitz [Instrumental Versions]","Yeah Yeah Yeahs","Post-Punk Revival",2009,"pics/album_yeahyeahyeahs_itsblitz.png"],
["","Softshock [Instrumental]","03:53",3,"It's Blitz [Instrumental Versions]","Yeah Yeah Yeahs","Post-Punk Revival",2009,"pics/album_yeahyeahyeahs_itsblitz.png"],
["","Skeletons [Instrumental]","05:02",4,"It's Blitz [Instrumental Versions]","Yeah Yeah Yeahs","Post-Punk Revival",2009,"pics/album_yeahyeahyeahs_itsblitz.png"],
["","Dull Life [Instrumental]","04:08",5,"It's Blitz [Instrumental Versions]","Yeah Yeah Yeahs","Post-Punk Revival",2009,"pics/album_yeahyeahyeahs_itsblitz.png"],
["","Shame And Fortune [Instrumental]","03:32",6,"It's Blitz [Instrumental Versions]","Yeah Yeah Yeahs","Post-Punk Revival",2009,"pics/album_yeahyeahyeahs_itsblitz.png"],
["","Runaway [Instrumental]","05:13",7,"It's Blitz [Instrumental Versions]","Yeah Yeah Yeahs","Post-Punk Revival",2009,"pics/album_yeahyeahyeahs_itsblitz.png"],
["","Dragon Queen [Instrumental]","04:02",8,"It's Blitz [Instrumental Versions]","Yeah Yeah Yeahs","Post-Punk Revival",2009,"pics/album_yeahyeahyeahs_itsblitz.png"],
["","Hysteric [Instrumental]","03:52",9,"It's Blitz [Instrumental Versions]","Yeah Yeah Yeahs","Post-Punk Revival",2009,"pics/album_yeahyeahyeahs_itsblitz.png"],
["","Little Shadow [Instrumental]","03:57",10,"It's Blitz [Instrumental Versions]","Yeah Yeah Yeahs","Post-Punk Revival",2009,"pics/album_yeahyeahyeahs_itsblitz.png"],
["","jailbreak","03:57",1,"Jailbreak","Thin Lizzy","Rock",,"pics/album_thinlizzy_jailbreak.png"],
["","angel from the coast","03:01",2,"Jailbreak","Thin Lizzy","Rock",,"pics/album_thinlizzy_jailbreak.png"],
["","running back","03:11",3,"Jailbreak","Thin Lizzy","Rock",,"pics/album_thinlizzy_jailbreak.png"],
["","romeo and the lonely girl","03:53",4,"Jailbreak","Thin Lizzy","Rock",,"pics/album_thinlizzy_jailbreak.png"],
["","fight or fall","03:42",5,"Jailbreak","Thin Lizzy","Rock",,"pics/album_thinlizzy_jailbreak.png"],
["","the boys are back in town","04:20",6,"Jailbreak","Thin Lizzy","Rock",,"pics/album_thinlizzy_jailbreak.png"],
["","warrior","04:03",7,"Jailbreak","Thin Lizzy","Rock",,"pics/album_thinlizzy_jailbreak.png"],
["","cowboy song","05:08",8,"Jailbreak","Thin Lizzy","Rock",,"pics/album_thinlizzy_jailbreak.png"],
["","emerald","03:58",9,"Jailbreak","Thin Lizzy","Rock",,"pics/album_thinlizzy_jailbreak.png"],
["","johnny","04:14",1,"Johnny The Fox","Thin Lizzy","Rock",,"pics/album_thinlizzy_johnnythefox.png"],
["","rocky","03:35",2,"Johnny The Fox","Thin Lizzy","Rock",,"pics/album_thinlizzy_johnnythefox.png"],
["","borderline","04:26",3,"Johnny The Fox","Thin Lizzy","Rock",,"pics/album_thinlizzy_johnnythefox.png"],
["","dont believe a word","02:14",4,"Johnny The Fox","Thin Lizzy","Rock",,"pics/album_thinlizzy_johnnythefox.png"],
["","fools gold","03:44",5,"Johnny The Fox","Thin Lizzy","Rock",,"pics/album_thinlizzy_johnnythefox.png"],
["","johnny the fox meets jimmy the","03:32",6,"Johnny The Fox","Thin Lizzy","Rock",,"pics/album_thinlizzy_johnnythefox.png"],
["","old flame","03:01",7,"Johnny The Fox","Thin Lizzy","Rock",,"pics/album_thinlizzy_johnnythefox.png"],
["","massacre","02:54",8,"Johnny The Fox","Thin Lizzy","Rock",,"pics/album_thinlizzy_johnnythefox.png"],
["","sweet marie","03:49",9,"Johnny The Fox","Thin Lizzy","Rock",,"pics/album_thinlizzy_johnnythefox.png"],
["","boogie woogie dance","03:01",10,"Johnny The Fox","Thin Lizzy","Rock",,"pics/album_thinlizzy_johnnythefox.png"],
["","Valentine","04:27",1,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","Roll River Roll","05:11",2,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","Serious","03:24",3,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","Tonight The Streets Are Ours","03:40",4,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","Lady Solitude","05:32",5,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","Dark Road","03:58",6,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","The Sea Calls","05:54",7,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","Ladys Bridge","04:00",8,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","Im Looking For Someone To Find","03:18",9,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","Our Darkness","04:08",10,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","The Sun Refused To Shine","04:57",11,"Ladys Bridge","Richard Hawley","Rock",,"pics/album_richardhawley_ladysbridge.png"],
["","jailbreak","04:33",1,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","emerald","04:34",2,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","southbound","04:43",3,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","rosalie","04:07",4,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","dancing in the moonlight","03:55",5,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","massacre","02:56",6,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","still in love with you","07:41",7,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","johnny the fox meets jimmy the","03:42",8,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","cowboy song","04:54",9,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","the boys are back in town","04:41",10,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","dont believe a word","02:19",11,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","warriors","04:01",12,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","are you ready","02:43",13,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","suicide","05:13",14,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","sha la la","05:34",15,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","baby drives me crazy","06:41",16,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","the rocker","04:18",17,"Live and Dangerous","Thin Lizzy","Rock",,"pics/album_thinlizzy_liveanddangerous.png"],
["","she knows","05:04",1,"Nightlife","Thin Lizzy","Rock",1974,"pics/album_thinlizzy_nightlife.png"],
["","night life","03:50",2,"Nightlife","Thin Lizzy","Rock",1974,"pics/album_thinlizzy_nightlife.png"],
["","its only money","02:42",3,"Nightlife","Thin Lizzy","Rock",1974,"pics/album_thinlizzy_nightlife.png"],
["","still in love with you","05:27",4,"Nightlife","Thin Lizzy","Rock",1974,"pics/album_thinlizzy_nightlife.png"],
["","frankie carroll","01:56",5,"Nightlife","Thin Lizzy","Rock",1974,"pics/album_thinlizzy_nightlife.png"],
["","showdown","04:23",6,"Nightlife","Thin Lizzy","Rock",1974,"pics/album_thinlizzy_nightlife.png"],
["","banshee","01:21",7,"Nightlife","Thin Lizzy","Rock",1974,"pics/album_thinlizzy_nightlife.png"],
["","philomena","03:34",8,"Nightlife","Thin Lizzy","Rock",1974,"pics/album_thinlizzy_nightlife.png"],
["","sha la la","03:20",9,"Nightlife","Thin Lizzy","Rock",1974,"pics/album_thinlizzy_nightlife.png"],
["","dear heart","04:24",10,"Nightlife","Thin Lizzy","Rock",1974,"pics/album_thinlizzy_nightlife.png"],
["","Time To Pretend","04:21",1,"Oracular Spectacular","MGMT","Alternative & Punk",2007,"pics/album_mgmt_oracularspectacular.png"],
["","Weekend Wars","04:12",2,"Oracular Spectacular","MGMT","Alternative & Punk",2007,"pics/album_mgmt_oracularspectacular.png"],
["","The Youth","03:48",3,"Oracular Spectacular","MGMT","Alternative & Punk",2007,"pics/album_mgmt_oracularspectacular.png"],
["","Electric Feel","03:50",4,"Oracular Spectacular","MGMT","Alternative & Punk",2007,"pics/album_mgmt_oracularspectacular.png"],
["","Kids","05:03",5,"Oracular Spectacular","MGMT","Alternative & Punk",2007,"pics/album_mgmt_oracularspectacular.png"],
["","4th Dimensional Transition","03:58",6,"Oracular Spectacular","MGMT","Alternative & Punk",2007,"pics/album_mgmt_oracularspectacular.png"],
["","Pieces Of What","02:44",7,"Oracular Spectacular","MGMT","Alternative & Punk",2007,"pics/album_mgmt_oracularspectacular.png"],
["","Of Moons, Birds & Monsters","04:47",8,"Oracular Spectacular","MGMT","Alternative & Punk",2007,"pics/album_mgmt_oracularspectacular.png"],
["","The Handshake","03:40",9,"Oracular Spectacular","MGMT","Alternative & Punk",2007,"pics/album_mgmt_oracularspectacular.png"],
["","Future Reflections","04:00",10,"Oracular Spectacular","MGMT","Alternative & Punk",2007,"pics/album_mgmt_oracularspectacular.png"],
["","i might have been queen","04:01",1,"Private Dancer","Tina Turner","Pop",1984,"pics/album_tinaturner_privatedancer.png"],
["","whats love got to do with it","03:41",2,"Private Dancer","Tina Turner","Pop",1984,"pics/album_tinaturner_privatedancer.png"],
["","show some respect","03:10",3,"Private Dancer","Tina Turner","Pop",1984,"pics/album_tinaturner_privatedancer.png"],
["","i cant stand the rain","03:36",4,"Private Dancer","Tina Turner","Pop",1984,"pics/album_tinaturner_privatedancer.png"],
["","private dancer","06:57",5,"Private Dancer","Tina Turner","Pop",1984,"pics/album_tinaturner_privatedancer.png"],
["","lets stay together","05:07",6,"Private Dancer","Tina Turner","Pop",1984,"pics/album_tinaturner_privatedancer.png"],
["","better be good to me","05:00",7,"Private Dancer","Tina Turner","Pop",1984,"pics/album_tinaturner_privatedancer.png"],
["","steel claw","03:42",8,"Private Dancer","Tina Turner","Pop",1984,"pics/album_tinaturner_privatedancer.png"],
["","help","04:24",9,"Private Dancer","Tina Turner","Pop",1984,"pics/album_tinaturner_privatedancer.png"],
["","1984","03:03",10,"Private Dancer","Tina Turner","Pop",1984,"pics/album_tinaturner_privatedancer.png"],
["","Jericho","03:44",1,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Music Reach 1/2/3/4","04:12",2,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Wind It Up","04:33",3,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Your Love","05:31",4,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Hyperspeed (G-Force Part 2)","05:15",5,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Charly (Trip Into Drum & Bass Version)","05:13",6,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Out Of Space","04:58",7,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Everybody In The Place (135 & Rising)","04:11",8,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Weather Experience","08:05",9,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Fire (Sunrise Version)","04:58",10,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Ruff In The Jungle Bizness","05:10",11,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","Death Of The Prodigy Dancers (Live)","03:43",12,"The Prodigy Experience","The Prodigy","Breakbeat",1992,"pics/album_prodigy_experience.png"],
["","angel of death","06:18",1,"Renegade","Thin Lizzy","Rock",,"pics/album_thinlizzy_renegade.png"],
["","renegade","06:09",2,"Renegade","Thin Lizzy","Rock",,"pics/album_thinlizzy_renegade.png"],
["","the pressure will blow","03:47",3,"Renegade","Thin Lizzy","Rock",,"pics/album_thinlizzy_renegade.png"],
["","leave this town","03:50",4,"Renegade","Thin Lizzy","Rock",,"pics/album_thinlizzy_renegade.png"],
["","hollywood","04:10",5,"Renegade","Thin Lizzy","Rock",,"pics/album_thinlizzy_renegade.png"],
["","no one told him","03:37",6,"Renegade","Thin Lizzy","Rock",,"pics/album_thinlizzy_renegade.png"],
["","fats","04:04",7,"Renegade","Thin Lizzy","Rock",,"pics/album_thinlizzy_renegade.png"],
["","mexican blood","03:42",8,"Renegade","Thin Lizzy","Rock",,"pics/album_thinlizzy_renegade.png"],
["","its getting dangerous","05:30",9,"Renegade","Thin Lizzy","Rock",,"pics/album_thinlizzy_renegade.png"],
["","Me I Disconnect From You","03:18",1,"Replicas","Tubeway Army","Rock",,"pics/album_tubewayarmy_replicas.png"],
["","Are Friends Electric","05:13",2,"Replicas","Tubeway Army","Rock",,"pics/album_tubewayarmy_replicas.png"],
["","The Machman","03:05",3,"Replicas","Tubeway Army","Rock",,"pics/album_tubewayarmy_replicas.png"],
["","Praying To The Aliens","03:45",4,"Replicas","Tubeway Army","Rock",,"pics/album_tubewayarmy_replicas.png"],
["","Down In The Park","04:19",5,"Replicas","Tubeway Army","Rock",,"pics/album_tubewayarmy_replicas.png"],
["","You Are In My Vision","03:06",6,"Replicas","Tubeway Army","Rock",,"pics/album_tubewayarmy_replicas.png"],
["","Replicas","04:52",7,"Replicas","Tubeway Army","Rock",,"pics/album_tubewayarmy_replicas.png"],
["","It Must Have Been Years","03:53",8,"Replicas","Tubeway Army","Rock",,"pics/album_tubewayarmy_replicas.png"],
["","When The Machines Rock","03:09",9,"Replicas","Tubeway Army","Rock",,"pics/album_tubewayarmy_replicas.png"],
["","I Almost Married A Human","06:12",10,"Replicas","Tubeway Army","Rock",,"pics/album_tubewayarmy_replicas.png"],
["","nomadic tribes","06:55",1,"Shades of a Blue Orphanage","Thin Lizzy","Rock",,"pics/album_thinlizzy_shadesofablueorphanage.png"],
["","buffalo gal","05:18",2,"Shades of a Blue Orphanage","Thin Lizzy","Rock",,"pics/album_thinlizzy_shadesofablueorphanage.png"],
["","i dont want to forget how to j","01:43",3,"Shades of a Blue Orphanage","Thin Lizzy","Rock",,"pics/album_thinlizzy_shadesofablueorphanage.png"],
["","sarah","02:45",4,"Shades of a Blue Orphanage","Thin Lizzy","Rock",,"pics/album_thinlizzy_shadesofablueorphanage.png"],
["","brought down","04:10",5,"Shades of a Blue Orphanage","Thin Lizzy","Rock",,"pics/album_thinlizzy_shadesofablueorphanage.png"],
["","baby face","03:18",6,"Shades of a Blue Orphanage","Thin Lizzy","Rock",,"pics/album_thinlizzy_shadesofablueorphanage.png"],
["","chatting today","04:13",7,"Shades of a Blue Orphanage","Thin Lizzy","Rock",,"pics/album_thinlizzy_shadesofablueorphanage.png"],
["","call the police","03:30",8,"Shades of a Blue Orphanage","Thin Lizzy","Rock",,"pics/album_thinlizzy_shadesofablueorphanage.png"],
["","shades of a blue orphanage","06:51",9,"Shades of a Blue Orphanage","Thin Lizzy","Rock",,"pics/album_thinlizzy_shadesofablueorphanage.png"],
["","Gold Lion","03:07",1,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","Way Out","02:51",2,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","Fancy","04:25",3,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","Phenomena","04:10",4,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","Honeybear","02:26",5,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","Cheated Hearts","03:58",6,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","Dudley","03:42",7,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","Mysteries","02:36",8,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","The Sweets","03:55",9,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","Warrior","03:43",10,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","Turn Into","04:08",11,"Show Your Bones [Bonus Track]","Yeah Yeah Yeahs","Rock",2006,"pics/album_yeahyeahyeahs_showyourbones.png"],
["","friendly ranger at clontarf ca","01:03",1,"Thin Lizzy","Thin Lizzy","Rock",,"pics/album_thinlizzy_thinlizzy.png"],
["","honesty is no excuse","05:33",2,"Thin Lizzy","Thin Lizzy","Rock",,"pics/album_thinlizzy_thinlizzy.png"],
["","diddy levine","06:54",3,"Thin Lizzy","Thin Lizzy","Rock",,"pics/album_thinlizzy_thinlizzy.png"],
["","ray gun","03:01",4,"Thin Lizzy","Thin Lizzy","Rock",,"pics/album_thinlizzy_thinlizzy.png"],
["","look what the wind blew in","03:19",5,"Thin Lizzy","Thin Lizzy","Rock",,"pics/album_thinlizzy_thinlizzy.png"],
["","eire","02:04",6,"Thin Lizzy","Thin Lizzy","Rock",,"pics/album_thinlizzy_thinlizzy.png"],
["","return of the farmers son","04:09",7,"Thin Lizzy","Thin Lizzy","Rock",,"pics/album_thinlizzy_thinlizzy.png"],
["","clifton grange hotel","02:24",8,"Thin Lizzy","Thin Lizzy","Rock",,"pics/album_thinlizzy_thinlizzy.png"],
["","saga of the ageing orphans","03:36",9,"Thin Lizzy","Thin Lizzy","Rock",,"pics/album_thinlizzy_thinlizzy.png"],
["","remembering","05:51",10,"Thin Lizzy","Thin Lizzy","Rock",,"pics/album_thinlizzy_thinlizzy.png"],
["","thunder and lightning","04:54",1,"Thunder and Lightning","Thin Lizzy","Rock",,"pics/album_thinlizzy_thunderandlightning.png"],
["","this is the one","04:04",2,"Thunder and Lightning","Thin Lizzy","Rock",,"pics/album_thinlizzy_thunderandlightning.png"],
["","the sun goes down","06:20",3,"Thunder and Lightning","Thin Lizzy","Rock",,"pics/album_thinlizzy_thunderandlightning.png"],
["","the holy war","05:13",4,"Thunder and Lightning","Thin Lizzy","Rock",,"pics/album_thinlizzy_thunderandlightning.png"],
["","cold sweat","03:07",5,"Thunder and Lightning","Thin Lizzy","Rock",,"pics/album_thinlizzy_thunderandlightning.png"],
["","someday she is going to hit ba","04:06",6,"Thunder and Lightning","Thin Lizzy","Rock",,"pics/album_thinlizzy_thunderandlightning.png"],
["","baby please dont go","05:10",7,"Thunder and Lightning","Thin Lizzy","Rock",,"pics/album_thinlizzy_thunderandlightning.png"],
["","bad habits","04:05",8,"Thunder and Lightning","Thin Lizzy","Rock",,"pics/album_thinlizzy_thunderandlightning.png"],
["","heart attack","03:40",9,"Thunder and Lightning","Thin Lizzy","Rock",,"pics/album_thinlizzy_thunderandlightning.png"],
["","Listen To The Sirens","03:02",1,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","My Shadow In Vain","02:56",2,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","The Life Machine","02:34",3,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","Friends","02:27",4,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","Something In The House","04:04",5,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","Everyday I Die","02:26",6,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","Steel And You","04:42",7,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","My Love Is A Liquid","03:27",8,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","Are You-real","03:22",9,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","The Dream Police","03:29",10,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","Jo The Waiter","02:39",11,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","Zero Bars","02:48",12,"Tubeway Army","Tubeway Army","Rock",,"pics/album_tubewayarmy_tubewayarmy.png"],
["","mama nature said","04:39",1,"Vagabond of the Western World","Thin Lizzy","Rock",1973,"pics/album_thinlizzy_vagabondsofthewesternworld.png"],
["","the hero and the madman","06:01",2,"Vagabond of the Western World","Thin Lizzy","Rock",1973,"pics/album_thinlizzy_vagabondsofthewesternworld.png"],
["","slow blues","05:08",3,"Vagabond of the Western World","Thin Lizzy","Rock",1973,"pics/album_thinlizzy_vagabondsofthewesternworld.png"],
["","the rocker","05:01",4,"Vagabond of the Western World","Thin Lizzy","Rock",1973,"pics/album_thinlizzy_vagabondsofthewesternworld.png"],
["","vagabond of the western world","04:29",5,"Vagabond of the Western World","Thin Lizzy","Rock",1973,"pics/album_thinlizzy_vagabondsofthewesternworld.png"],
["","little girl in bloom","05:02",6,"Vagabond of the Western World","Thin Lizzy","Rock",1973,"pics/album_thinlizzy_vagabondsofthewesternworld.png"],
["","gonna creep up on you","03:19",7,"Vagabond of the Western World","Thin Lizzy","Rock",1973,"pics/album_thinlizzy_vagabondsofthewesternworld.png"],
["","hanuman","03:43",1,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","buster voodoo","04:24",2,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","triveni","03:56",3,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","logos","02:51",4,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","santo domingo","04:03",5,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","master maqui","05:06",6,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","savitri","03:47",7,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","hora zero","05:25",8,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","chac mool","01:51",9,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","atman","05:51",10,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","11-11","04:50",11,"11-11","rodrigo y gabriela","World",2009,"pics/album_rodrigoygabriela_1111.png"],
["","Harlems Nocturne","01:44",1,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Karma","04:16",2,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Heartburn","03:28",3,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","If I Was Your Woman (Walk On By)","03:06",4,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","You Don't Know My Name","06:07",5,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","If I Aint Got You","03:49",6,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Diary (Featuring Tony! Toni! Tone!)","04:44",7,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Dragon Days","04:37",8,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Wake Up","04:27",9,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","So Simple","03:50",10,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","When You Really Love Someone","04:10",11,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Feeling You Feeling Me (Interlude)","02:08",12,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Slow Down","04:18",13,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Samsonite Man","04:13",14,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Nobody Not Really (Interlude)","03:11",15,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Streets Of NY (Featuring Nas & Rakim)","04:55",16,"Alicia Keys - The Diary of Alicia Keys","Alicia Keys","R&B",2003,"pics/Alicia Keys - The Diary of Alicia Keys.pict.png"],
["","Rehab (Album Version)","03:34",1,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","You Know I'm No Good","04:17",2,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","Me & Mr Jones","02:32",3,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","Just Friends","03:12",4,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","Back to Black","04:00",5,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","Love Is a Losing Game","02:34",6,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","Tears Dry on Their Own","03:05",7,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","Wake Up Alone","03:41",8,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","Some Unholy War","02:21",9,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","He Can Only Hold Her","02:45",10,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","Addicted","02:45",11,"Back to Black (UK Version)","Amy Winehouse","R&B/Soul",2006,"pics/Back to Black.pict.png"],
["","Can't Take My Eyes Off You","03:14",17,"40 Greatest Ever Love Songs","Andy Williams","Alternative & Punk",1967,"pics/album_no_artwork.png"],
["","Brianstorm","02:50",1,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","Teddy Picker","02:43",2,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","D Is For Dangerous","02:16",3,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","Balaclava","02:49",4,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","Fluorescent Adolescent","02:58",5,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","Only Ones Who Know","03:03",6,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","Do Me A Favour","03:27",7,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","This House Is A Circus","03:10",8,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","If You Were There, Beware","04:34",9,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","The Bad Thing","02:23",10,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","Old Yellow Bricks","03:11",11,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","505","04:14",12,"Favourite Worst Nightmare","Arctic Monkeys","Alternative & Punk",2007,"pics/Favourite Worst Nightmare.pict.png"],
["","The View From The Afternoon","03:38",1,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","I Bet You Look Good On The Dancefloor","02:54",2,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","Fake Tales Of San Francisco","02:58",3,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","Dancing Shoes","02:21",4,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","You Probably Couldn't See For The Lights But You Were Staring Straight At Me","02:11",5,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","Still Take You Home","02:54",6,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","Riot Van","02:15",7,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","Red Light Indicates Doors Are Secured","02:24",8,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","Mardy Bum","02:55",9,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","Perhaps Vampires Is A Bit Strong But...","04:29",10,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","When The Sun Goes Down","03:20",11,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","From The Ritz To The Rubble","03:13",12,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","A Certain Romance","05:31",13,"Whatever People Say I Am, That's What I'm Not","Arctic Monkeys","Alternative & Punk",2006,"pics/Whatever People Say I Am.pict.png"],
["","Lose Control","03:38",1,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","Goldfinger","04:32",2,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","Girl From Mars","03:30",3,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","I'd Give You Anything","04:32",4,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","Gone The Dream","03:30",5,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","Kung Fu","02:17",6,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","Oh Yeah","04:45",7,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","Let It Flow","04:43",8,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","Innocent Smile","05:52",9,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","Angel Interceptor","04:04",10,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","Lost In You","04:19",11,"1977","Ash","Alternative & Punk",1996,"pics/1977.pict.png"],
["","Ladies Night","03:08",1,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Be With You","03:38",2,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Don't Go Breaking My Heart","03:43",3,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","If You Come To Me","03:46",4,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Believer","03:46",5,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Everything Goes Around","03:06",6,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Somebody Like You","03:57",7,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Nothing In The World","03:59",8,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Always Be My Baby","03:20",9,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","I Won't Be There","03:53",10,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Never Get Over You","03:57",11,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Don't You Know","03:24",12,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Loving You","03:12",13,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Don't Let Me Down","03:40",14,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Someone Like Me","02:07",15,"Ladies Night","Atomic Kitten","Pop",2003,"pics/Ladies Night.pict.png"],
["","Night Fever","03:29",2,"Bee Gees: Greatest (Bonus Video Version) [Remastered]","Bee Gees","Rock",1978,"pics/album_no_artwork.png"],
["","Stayin' Alive","04:45",5,"Bee Gees: Greatest (Bonus Video Version) [Remastered]","Bee Gees","Rock",1978,"pics/album_no_artwork.png"],
["","Nobody's Fault But Mine","03:50",1,"Violets - EP","Beth Rowley","R&B/Soul",2007,"pics/Violets - EP.pict.png"],
["","Intro (Good Morning World)","00:29",1,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Made It Back","04:09",2,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Rewind (Find A Way)","04:28",3,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Damn","04:52",4,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","A.W.O.L.","04:30",5,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Sista, Sista","04:42",6,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Strong Hand","03:20",7,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Greatest Day","04:16",8,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","That's Alright","04:19",9,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Tomorrow","04:42",10,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Send Me, Move Me, Love Me","05:05",11,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","The Need OF You","03:45",12,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Good Morning World","05:43",13,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Made It Back '99 (Good Times Mix) Featuring Redman","03:39",14,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","A.W.O.L. (Jus Bounce Mix)","04:08",15,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Greatest Day (Classic Mix)","04:15",16,"Prodigal Sista","Beverley Knight","R&B",1999,"pics/Prodigal Sista.pict.png"],
["","Heart Of Glass","04:34",1,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","Denis","02:18",2,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","The Tide Is High","04:40",3,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","In The Flesh","02:31",4,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","Sunday Girl","03:04",5,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","Dreaming","03:07",6,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","Hanging On The Telephone","02:22",7,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","Rpture","05:35",8,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","Picture This","02:58",9,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","Union City Blue","03:22",10,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","(I'm All Ways Touched By Your) Presence Dear","02:42",11,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","Call Me","03:32",12,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","Atomic","04:40",13,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","Rip Her To Shreds","03:22",14,"The Best Of Blondie","Blondie","Rock",1989,"pics/The Best Of Blondie.pict.png"],
["","I Don't Like Mondays","04:19",1,"Loudmouth - The Best of Bob Geldof & the Boomtown Rats","The Boomtown Rats","Rock",1978,"pics/Loudmouth.pict.png"],
["","Is This Love","03:51",1,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","No Woman, No Cry (Live)","07:08",2,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Could You Be Loved","03:57",3,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Three Little Birds","03:00",4,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Buffalo Soldier","04:18",5,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Get Up, Stand Up","03:17",6,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Stir It Up","05:31",7,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Easy Skanking","02:57",8,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","One Love / People Get Ready","02:52",9,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","I Shot the Sheriff","04:40",10,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Waiting In Vain (Alternate Version)","04:17",11,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Redemption Song","03:48",12,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Satisfy My Soul","04:31",13,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Exodus","07:40",14,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Jamming (Long Version)","03:31",15,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Punky Reggae Party (Long Version)","06:52",16,"Legend (Bonus Tracks)","Bob Marley","Reggae",2002,"pics/Legend.pict.png"],
["","Livin' On A Prayer","04:11",1,"Cross Road","Bon Jovi","Rock",1986,"pics/Cross Road.pict.png"],
["","Keep The Faith","05:45",2,"Cross Road","Bon Jovi","Rock",1992,"pics/Cross Road.pict.png"],
["","Someday I'll Be Saturday Night","04:40",3,"Cross Road","Bon Jovi","Rock",1995,"pics/Cross Road.pict.png"],
["","Always","05:53",4,"Cross Road","Bon Jovi","Rock",1994,"pics/Cross Road.pict.png"],
["","Wanted Dead Or Alive","05:08",5,"Cross Road","Bon Jovi","Rock",1986,"pics/Cross Road.pict.png"],
["","Lay Your Hands On Me","05:59",6,"Cross Road","Bon Jovi","Rock",1988,"pics/Cross Road.pict.png"],
["","You Give Love A Bad Name","03:44",7,"Cross Road","Bon Jovi","Rock",1986,"pics/Cross Road.pict.png"],
["","Bed Of Roses","06:35",8,"Cross Road","Bon Jovi","Rock",1992,"pics/Cross Road.pict.png"],
["","Blaze Of Glory","05:40",9,"Cross Road","Bon Jovi","Rock",1990,"pics/Cross Road.pict.png"],
["","In These Arms","05:19",10,"Cross Road","Bon Jovi","Rock",1992,"pics/Cross Road.pict.png"],
["","Bad Medicine","05:17",11,"Cross Road","Bon Jovi","Rock",1988,"pics/Cross Road.pict.png"],
["","I'll Be There For You","05:42",12,"Cross Road","Bon Jovi","Rock",1988,"pics/Cross Road.pict.png"],
["","In & Out Of Love","04:27",13,"Cross Road","Bon Jovi","Rock",1986,"pics/Cross Road.pict.png"],
["","Runaway","03:53",14,"Cross Road","Bon Jovi","Rock",1984,"pics/Cross Road.pict.png"],
["","Never Say Goodbye","04:51",15,"Cross Road","Bon Jovi","Rock",1986,"pics/Cross Road.pict.png"],
]
